


export const PEDIR_CONDUCTORA ="PEDIR_CONDUCTORA"
export const ORIGEN ="ORIGEN";
export const DESTINO="DESTINO";
export const TIEMPO_DE_VIAJE ="TIEMPO_DE_VIAJE";

export const FILTRAR_CONDUCTORA_SEGUN_AUTO = 'FILTRO_CONDUCTORA_SEGUN_AUTO'