export const PEDIR_CONDUCTORA="PEDIR_CONDUCTORA"
export const INFO_PASAJERA_REQUEST = "INFO_PASAJERA_REQUEST"
export const INFO_PASAJERA_SUCCESS = "INFO_PASAJERA_SUCCESS"
export const INFO_PASAJERA_FAIL = "INFO_PASAJERA_FAIL"


