export const PEDIR_CONDUCTORA = "PEDIR_CONDUCTORA";
export const DETALLE_CONDUCTORA="DETALLE_CONDUCTORA";
export const FILTRAR_CONDUCTORA_SEGUN_AUTO = 'FILTRO_CONDUCTORA_SEGUN_AUTO'
export const INFO_PASAJERA_REQUEST = "INFO_PASAJERA_REQUEST"
export const INFO_PASAJERA_SUCCESS = "INFO_PASAJERA_SUCCESS"
export const INFO_PASAJERA_FAIL = "INFO_PASAJERA_FAIL"
export const ORIGEN = "ORIGEN";
export const DESTINO = "DESTINO";
export const TIEMPO_DE_VIAJE = "TIEMPO_DE_VIAJE";



export const GET_ALL_CONDUCTORAS = 'GET_ALL_CONDUCTORAS';
export const OBTENER_TODAS_LAS_PASAJERAS = 'OBTENER_TODAS_LAS_PASAJERAS';
export const OBTENER_PASAJERA_POR_ID = 'OBTENER_PASAJERA_POR_ID';
export const OBTENER_CONDUCTORA_POR_ID = 'OBTENER_CONDUCTORA_POR_ID';
export const LIMPIAR_DETALLE = 'LIMPIAR_DETALLE';
export const VERIFICAR_CONDUCTORA = 'VERIFICAR_CONDUCTORA';
export const DAR_BAJA_CONDUCTORA = 'DAR_BAJA_CONDUCTORA';
export const DAR_ALTA = 'DAR_ALTA';


// export const GET_CONDUNCTORAS_NAME= 'GET_CONDUNCTORAS_NAME';
// export const CONDUCTORAS_DETAIL= 'CONDUCTORAS_DETAIL';
export const POST_CONDUCTORAS='POST_CONDUCTORAS'
export const GET_PERFILC = 'GET_PERFILC'
export const LOGIN_COND_SUCCESS = 'LOGIN_COND_SUCCESS'
export const LOGIN_COND_ERROR = 'LOGIN_COND_ERROR'




///////////////////Autenticacion y usuario/////////////////////////////

export const LOGIN_USER_ERROR="LOGIN_USER_ERROR"
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS"
export const REGISTER_USER_ERROR="REGISTER_USER_ERROR"
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS"
export const LOGOUT_USER="LOGOUT_USER"
export const GET_USER_DETAILS="GET_USER_DETAILS"
export const AUTHENTICATION_ERROR="AUTHENTICATION_ERROR"
export const UPDATE_USER="UPDATE_USER"
export const RESET_PASSWORD="RESET_PASSWORD"
export const RELOADING_PAG="RELOADING_PAG"


////////////////////////////////////////////////////////////////////////

